- name: Setup Redis and Frontend Server
  hosts:
    - ubuntu
    - rocky
  become: true
  gather_facts: yes

  vars:
    # Set remote_user conditionally for each server role
    ansible_user: "{{ 'rocky' if 'server_role_redis_server' in group_names else 'ubuntu' }}"

  roles:
    - { role: redis, when: "'server_role_redis_server' in group_names" }
    - { role: frontend, when: "'server_role_frontend_server' in group_names" }
